repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.24.0
    hooks:
      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go.
        entry: golangci-lint run ./...
        types: [go]
        language: golang
        pass_filenames: false